services:
  # 1. PostgreSQL (For Users and Orders)
  postgres_db:
    image: postgres:15-alpine
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_password
      POSTGRES_DB: nexus_core_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB (For the Flexible Product Catalog)
  mongo_db:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Redis (for fast caching and shopping cart operations)
  redis_cache:
    image: redis:7-alpine
    container_name: nexus_redis
    restart: always
    ports:
      - "6379:6379"

  # 4. Backend API (brain of the system)
  backend_api:
    build: ./backend
    container_name: nexus_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  
    depends_on:
      - postgres_db
      - mongo_db
      - redis_cache    

volumes:
  postgres_data:
  mongo_data:
